<template>
  <div>
    <h1>Scrolling Animations, yaaay</h1>
    <p>
      <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam at autem cupiditate deserunt eos esse necessitatibus nihil nulla numquam odio quam quasi soluta suscipit, temporibus ut velit vero!</span><span>Ab ad aperiam aut cupiditate exercitationem, facilis id iure perferendis praesentium, soluta tempore voluptatum! Asperiores assumenda consequatur doloribus id, molestias nesciunt nihil perspiciatis veritatis! Doloribus fuga harum magni mollitia non!</span><span>A ab, animi corporis, dicta eaque inventore officiis perspiciatis porro quasi quis reprehenderit totam voluptatem voluptatum? Aut corporis dolores fugiat illum odio recusandae rem vero vitae. Deserunt iste nihil sunt!</span><span>Accusantium ad dolor quis. Architecto consectetur consequatur facilis fuga obcaecati pariatur placeat quia reprehenderit soluta vel! Cupiditate delectus dolore et, explicabo fugiat fugit, hic maxime mollitia nostrum provident qui rerum?</span><span>Ab aliquid architecto aut cumque cupiditate dolore, doloremque eligendi esse maxime non porro quae temporibus ullam voluptatibus voluptatum! Animi atque deserunt dolorem eius esse ipsum nemo officiis quaerat voluptate. Perferendis!</span><span>Excepturi incidunt maxime natus quaerat, repellendus sed vero! Accusamus alias architecto atque consectetur, eius est explicabo illo ipsa iste, itaque libero odit possimus, quaerat quas quis ratione similique tenetur vitae!</span><span>Distinctio illum mollitia nemo tempore? Amet atque eius ex exercitationem expedita libero mollitia nesciunt nulla quasi quis reiciendis, sunt tenetur totam! Accusantium debitis distinctio excepturi facilis harum impedit maiores porro!</span><span>Aspernatur exercitationem id molestiae non sint. Aliquam aspernatur dolorem dolores dolorum esse est illo laborum nam nobis obcaecati praesentium, quam repellat repellendus rerum sapiente, similique temporibus vel. Et, nostrum, reiciendis?</span>
      <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam at autem cupiditate deserunt eos esse necessitatibus nihil nulla numquam odio quam quasi soluta suscipit, temporibus ut velit vero!</span><span>Ab ad aperiam aut cupiditate exercitationem, facilis id iure perferendis praesentium, soluta tempore voluptatum! Asperiores assumenda consequatur doloribus id, molestias nesciunt nihil perspiciatis veritatis! Doloribus fuga harum magni mollitia non!</span><span>A ab, animi corporis, dicta eaque inventore officiis perspiciatis porro quasi quis reprehenderit totam voluptatem voluptatum? Aut corporis dolores fugiat illum odio recusandae rem vero vitae. Deserunt iste nihil sunt!</span><span>Accusantium ad dolor quis. Architecto consectetur consequatur facilis fuga obcaecati pariatur placeat quia reprehenderit soluta vel! Cupiditate delectus dolore et, explicabo fugiat fugit, hic maxime mollitia nostrum provident qui rerum?</span><span>Ab aliquid architecto aut cumque cupiditate dolore, doloremque eligendi esse maxime non porro quae temporibus ullam voluptatibus voluptatum! Animi atque deserunt dolorem eius esse ipsum nemo officiis quaerat voluptate. Perferendis!</span><span>Excepturi incidunt maxime natus quaerat, repellendus sed vero! Accusamus alias architecto atque consectetur, eius est explicabo illo ipsa iste, itaque libero odit possimus, quaerat quas quis ratione similique tenetur vitae!</span><span>Distinctio illum mollitia nemo tempore? Amet atque eius ex exercitationem expedita libero mollitia nesciunt nulla quasi quis reiciendis, sunt tenetur totam! Accusantium debitis distinctio excepturi facilis harum impedit maiores porro!</span><span>Aspernatur exercitationem id molestiae non sint. Aliquam aspernatur dolorem dolores dolorum esse est illo laborum nam nobis obcaecati praesentium, quam repellat repellendus rerum sapiente, similique temporibus vel. Et, nostrum, reiciendis?</span>
      <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam at autem cupiditate deserunt eos esse necessitatibus nihil nulla numquam odio quam quasi soluta suscipit, temporibus ut velit vero!</span><span>Ab ad aperiam aut cupiditate exercitationem, facilis id iure perferendis praesentium, soluta tempore voluptatum! Asperiores assumenda consequatur doloribus id, molestias nesciunt nihil perspiciatis veritatis! Doloribus fuga harum magni mollitia non!</span><span>A ab, animi corporis, dicta eaque inventore officiis perspiciatis porro quasi quis reprehenderit totam voluptatem voluptatum? Aut corporis dolores fugiat illum odio recusandae rem vero vitae. Deserunt iste nihil sunt!</span><span>Accusantium ad dolor quis. Architecto consectetur consequatur facilis fuga obcaecati pariatur placeat quia reprehenderit soluta vel! Cupiditate delectus dolore et, explicabo fugiat fugit, hic maxime mollitia nostrum provident qui rerum?</span><span>Ab aliquid architecto aut cumque cupiditate dolore, doloremque eligendi esse maxime non porro quae temporibus ullam voluptatibus voluptatum! Animi atque deserunt dolorem eius esse ipsum nemo officiis quaerat voluptate. Perferendis!</span><span>Excepturi incidunt maxime natus quaerat, repellendus sed vero! Accusamus alias architecto atque consectetur, eius est explicabo illo ipsa iste, itaque libero odit possimus, quaerat quas quis ratione similique tenetur vitae!</span><span>Distinctio illum mollitia nemo tempore? Amet atque eius ex exercitationem expedita libero mollitia nesciunt nulla quasi quis reiciendis, sunt tenetur totam! Accusantium debitis distinctio excepturi facilis harum impedit maiores porro!</span><span>Aspernatur exercitationem id molestiae non sint. Aliquam aspernatur dolorem dolores dolorum esse est illo laborum nam nobis obcaecati praesentium, quam repellat repellendus rerum sapiente, similique temporibus vel. Et, nostrum, reiciendis?</span>
      <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam at autem cupiditate deserunt eos esse necessitatibus nihil nulla numquam odio quam quasi soluta suscipit, temporibus ut velit vero!</span><span>Ab ad aperiam aut cupiditate exercitationem, facilis id iure perferendis praesentium, soluta tempore voluptatum! Asperiores assumenda consequatur doloribus id, molestias nesciunt nihil perspiciatis veritatis! Doloribus fuga harum magni mollitia non!</span><span>A ab, animi corporis, dicta eaque inventore officiis perspiciatis porro quasi quis reprehenderit totam voluptatem voluptatum? Aut corporis dolores fugiat illum odio recusandae rem vero vitae. Deserunt iste nihil sunt!</span><span>Accusantium ad dolor quis. Architecto consectetur consequatur facilis fuga obcaecati pariatur placeat quia reprehenderit soluta vel! Cupiditate delectus dolore et, explicabo fugiat fugit, hic maxime mollitia nostrum provident qui rerum?</span><span>Ab aliquid architecto aut cumque cupiditate dolore, doloremque eligendi esse maxime non porro quae temporibus ullam voluptatibus voluptatum! Animi atque deserunt dolorem eius esse ipsum nemo officiis quaerat voluptate. Perferendis!</span><span>Excepturi incidunt maxime natus quaerat, repellendus sed vero! Accusamus alias architecto atque consectetur, eius est explicabo illo ipsa iste, itaque libero odit possimus, quaerat quas quis ratione similique tenetur vitae!</span><span>Distinctio illum mollitia nemo tempore? Amet atque eius ex exercitationem expedita libero mollitia nesciunt nulla quasi quis reiciendis, sunt tenetur totam! Accusantium debitis distinctio excepturi facilis harum impedit maiores porro!</span><span>Aspernatur exercitationem id molestiae non sint. Aliquam aspernatur dolorem dolores dolorum esse est illo laborum nam nobis obcaecati praesentium, quam repellat repellendus rerum sapiente, similique temporibus vel. Et, nostrum, reiciendis?</span>
    </p>
  </div>
</template>

<style scoped>

div {
  display: flex;
  flex-direction: column;
  align-items: center;
}

p {
  width: 300px;
  text-align: center;
}
</style>
